[server]
port = 22 
host_key_file = "host_key" 
force_command = "entrypoint.sh" 
forceonexit = "echo $NICK"

proxy_protocol_enabled = true 
proxy_allowed_ips = "127.0.0.1/32,192.168.1.0/24" 
real_ip_fallback = "127.0.0.1" 


[nickserv]
api_url = "http://localhost:8089/v1/check_auth"
register_api_url = "http://localhost:8089/v1/saregister"
api_token = ""
allow_registration_on_fail = true